- apt-get:
  - git
  - curl
  - wget
  - tree
  - zsh
  - vim
  - tmux
  - jdupes
  - htop
  - zip
  - unzip
  - iftop
  - nethogs
#  - ripgrep
# curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
# sudo dpkg -i ripgrep_13.0.0_amd64.deb
